# URL to download the AppDynamics installer. Preferably use an internal URL like artifactory.
download_url: "https://download.appdynamics.com/path/to/appdynamics/installer" # use artifactory or any other internal URL

# Path where the AppDynamics installer will be downloaded.
installer_path: "/tmp/appdynamics_installer.sh"

# Directory where AppDynamics will be installed.
installation_directory: "/opt/appdynamics"

# Username for AppDynamics authentication.
appd_username: "{{ lookup('env', 'APPD_USERNAME') }}" # Use it as an environment variable

# Password for AppDynamics authentication. Ensure this is stored securely.
appd_password: "{{ lookup('env', 'APPD_PASSWORD') }}" # Use it as an environment variable

# License key for AppDynamics. Ensure this is stored securely.
appd_license_key: "{{ lookup('env', 'APPD_LICENSE_KEY') }}" # Use it as an environment variable, if it is needed in the internal app
