name: Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Runs on the 1st and 15th day of even months (February, April, June, August, October, December)
    - cron: '0 0 1,15 2,4,6,8,10,12 *'
    # Runs on the 1st, 10th, and 20th day of odd months (January, March, May, July, September, November)
    - cron: '0 0 1,10,20 1,3,5,7,9,11 *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        severity: 'HIGH,CRITICAL'
        ignore-unfixed: true

    - name: Run Trivy scan and save results
      run: |
        mkdir -p logs
        trivy fs --severity HIGH,CRITICAL . > logs/scan-results-$(date +'%Y-%m-%d').log

    - name: Commit and push log file
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name 'Vineet Rana'
        git config --global user.email 'vineetrana2208@gmail.com'
        git add logs/scan-results-$(date +'%Y-%m-%d').log
        git commit -m "Add scan results for $(date +'%Y-%m-%d')"
        git push https://vineetranaji:${{ secrets.PAT_TOKEN }}@github.com/vineetranaji/appdynamics-using-ansible.git HEAD:main
